name: ci
'on':
  - push
  - pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v3.1.0
        with:
          node-version: 16
      - run: npm install
      - run: npm run build --if-present
      - run: echo "127.0.0.1 airtap.local" | sudo tee -a /etc/hosts
      - run: npm run lint
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
